version: "3.9"


services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fyp-network
    ports:
      - "5433:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    networks:
      - fyp-network
    ports:
      - "8080:5050"
    depends_on:
      - postgres

networks:
  fyp-network:
    external: true